---

- include_tasks: setup-RedHat.yaml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yaml
  when: ansible_os_family == 'Debian'

- name: Install Docker.
  package:
    name: "{{ docker_package }}"
    state: "{{ docker_package_state }}"
  notify: restart docker

# TODO: Remove this shim once 18.09.1 or later is released.
- import_tasks: docker-1809-shim.yaml
  when: ansible_service_mgr == 'systemd'

- name: Ensure docker systemd script use only socket when TLS disabled
  lineinfile:
    path: '{{ docker_systemd_script_path | default("/lib/systemd/system/docker.service") }}'
    regexp: '^ExecStart='
    line: 'ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock'
  when: docker_tls.enabled is undefined or docker_tls.enabled ==None or not docker_tls.enabled
  notify: restart docker
  tags:
    - docker
    - tls

- name: Ensure Docker is started and enabled at boot.
  systemd:
    name: docker
    state: "{{ docker_service_state }}"
    enabled: "{{ docker_service_enabled }}"
    daemon_reload: yes

- name: Ensure handlers are notified now to avoid firewall conflicts.
  meta: flush_handlers

- include_tasks: docker-compose.yaml
  when: docker_install_compose

- include_tasks: docker-users.yaml
  when: docker_users

- include_tasks: docker_tls.yaml
  when: docker_tls.enabled is defined and docker_tls.enabled != None and docker_tls.enabled
  tags:
    - docker
    - tls

- include_tasks: configure_docker.yaml
  when: docker_configuration is defined and docker_configuration != None
  tags:
    - docker
    - configure